### ISSUE TITLE
why need Uvicorn?

### ISSUE THREAD

**Issue by prprprus** [tiangolo/uvicorn-gunicorn-machine-learning-docker#3]
Hi @tiangolo 

As far as I understand, Uvicorn is a single process, which is very unfavorable for CPU-bound ML tasks. Why not just use gunicorn? If you add an extra layer of Uvicorn, it should increase performance consumption. It is this harmful to online prediction services. I look forward to your advice.

**Comment by tiangolo** [comment]
Please check the docs: https://github.com/tiangolo/uvicorn-gunicorn-machine-learning-docker#technical-details
