### ISSUE TITLE
Will CUDA version be updated to 10.1 version?

### ISSUE THREAD

**Issue by Lelthar** [tiangolo/uvicorn-gunicorn-machine-learning-docker#4]
Hi @tiangolo 

I want to use TensorFlow 2.2 using gpu in my project, but in a Tensorflow 2.2 project CUDA 10.1 is required. Will it be updated in the future?

Thanks

**Comment by tiangolo** [comment]
Hey there! I'm sorry, I'm currently not using this Docker image, so I wouldn't be able to promise much. You can probably extract some bits and pieces from the current files in case that's useful, but I won't be able to work on it much any time soon.
